# Setup
title:               Lewis Gudgeon
tagline:             ''
description:         ''
url:                 http://www.lewisgudgeon.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lewis Gudgeon
  url:               https://twitter.com/ljfgudgeon
  email:             ljfgudgeon@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Custom vars
version:             1
google_analytics_id: #UA-XXXX-Y
