# Setup
title:               Lewis Gudgeon
tagline:             ''
description:         ''
url:                 http://www.lewisgudgeon.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lewis Gudgeon
  url:               https://twitter.com/ljfgudgeon
  email:             ljfgudgeon@gmail.com

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]

# Custom vars
version:             1
google_analytics_id: #UA-XXXX-Y

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
